# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_prod.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_sel(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(391, 228)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_id = QtWidgets.QLabel(self.groupBox)
        self.label_id.setObjectName("label_id")
        self.horizontalLayout.addWidget(self.label_id)
        self.label_id_2 = QtWidgets.QLabel(self.groupBox)
        self.label_id_2.setText("")
        self.label_id_2.setObjectName("label_id_2")
        self.horizontalLayout.addWidget(self.label_id_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_ProdName = QtWidgets.QLabel(self.groupBox)
        self.label_ProdName.setObjectName("label_ProdName")
        self.horizontalLayout_2.addWidget(self.label_ProdName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_2.addWidget(self.lineEdit_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ProdReit = QtWidgets.QLabel(self.groupBox)
        self.label_ProdReit.setObjectName("label_ProdReit")
        self.horizontalLayout_3.addWidget(self.label_ProdReit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lineEdit_bdate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_bdate.setObjectName("lineEdit_bdate")
        self.horizontalLayout_3.addWidget(self.lineEdit_bdate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_ProdMagaz = QtWidgets.QLabel(self.groupBox)
        self.label_ProdMagaz.setObjectName("label_ProdMagaz")
        self.horizontalLayout_4.addWidget(self.label_ProdMagaz)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.pushButtonProd = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonProd.setObjectName("pushButtonProd")
        self.verticalLayout_2.addWidget(self.pushButtonProd)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Изменение продавца"))
        self.label_id.setText(_translate("Dialog", "id"))
        self.label_ProdName.setText(_translate("Dialog", "ФИО"))
        self.label_ProdReit.setText(_translate("Dialog", "Рейтинг"))
        self.label_ProdMagaz.setText(_translate("Dialog", "Название магазина"))
        self.pushButtonProd.setText(_translate("Dialog", "Сохранить"))
